export const USER_LOADING ="USER_LOADING";
export const LOGIN_USER ="LOGIN_USER";
export const REGISTER_USER ="REGISTER_USER";
export const LOGOUT_USER="LOGOUT_USER";
export const GET_AUTH_USER='GET_AUTH_USER';
export const AUTH_ERROS='AUTH_ERRORS';
export const REST_PASSWORD='REST_PASSWORD';
export const GET_AUTH_USER02='GET_AUTH_USER';
export const GETALLCOMMUNTE='GETALLCOMUNTE'
export const ADDPRDUCT='ADDPRDUCT'
export const ErroreProduct='ErroreProduct'
export const PRODUCT_LIST='PRODUCT_LIST'
export const DELETEPRODUCT="DELETEPRODUCT"